### ISSUE TITLE
How to write a .d.tl file for a framework (or something that isn't `require`d))

### ISSUE THREAD

**Issue by euclidianAce** [teal-language/teal-types#11]
I am working on a .d.tl file for Neovim's Lua api, but since Neovim itself runs the code, there is no `require("vim")`. Putting `preload_modules = {"vim"}` causes a 
```
Error: could not preload module 'vim'
```

In addition, frameworks like busted would have the same issues

**Comment by pdesaulniers** [comment]
If you get `Error: could not preload module 'vim'`, then maybe `vim.d.tl` is not available in the module path?

**Comment by euclidianAce** [comment]
Okay, I guess I had the search path wrong, but now with
```
print(vim.fn.mode()) -- script1.tl
```
(where `vim.fn is {string:function}`)
I get `script1.tl:1:7: unknown variable: vim`, but
```
print(require("vim").fn.mode()) -- script2.tl
```
works just fine
```
$ tl check script2.tl 
========================================
Type checked script2.tl
0 errors detected -- you can use:

   tl run script2.tl

       to run script2.tl as a program

   tl gen script2.tl

       to generate script2.lua
```

**Comment by pdesaulniers** [comment]
Maybe the `vim` record is local instead of global? Basically, what `preload_modules` does is this:
```
require("vim")
print(vim.fn.mode())
```

**Comment by euclidianAce** [comment]
Ah, that makes sense. When doing Lua things I usually forget that globals are actually a thing.

Thanks.

**Comment by tooolbox** [comment]
I had this question, I'm glad it's answered here but maybe it deserves a note in the Readme or an FAQ.  I.e., if you want to write a `.d.tl` file for functions that are available natively in a particular Lua environment, that don't need to be `required`, how do you do this?  So the answer is `preload_modules` or actually now `global_env_def` which is actually [covered here](https://github.com/teal-language/tl/blob/v0.13.0/docs/compiler_options.md#global-environment-definition) quite nicely, but again might be useful to have it called out in this repo.  Could perhaps even accumulate `.d.tl` files here for various environments, in addition to packages.

**Comment by pdesaulniers** [comment]
At least, I think we could add a "How to use" section at the top of the README which redirects towards the tl documentation.

With that said, the documentation regarding declaration files appear to be spread at two different locations right now:

- https://github.com/teal-language/tl/blob/v0.13.0/docs/tutorial.md#using-tl-with-lua
- https://github.com/teal-language/tl/blob/v0.13.0/docs/compiler_options.md#global-environment-definition

Maybe it would make sense to combine this information into a single `declaration_files.md` document.
