### ISSUE TITLE
Error: could not predefine module 'types'

### ISSUE THREAD

**Issue by B4mbus** [teal-language/teal-types#40]
I'm trying to generate types for neovim, I cloned the repo, copied the files from `types/neovim/*` to the root directory and ran `./autogen`, tho I'm getting the error
```
Error: could not predefine module 'types'
```
It's caused by the first command: `tl check autogen_tl -q`

**Comment by hishamhm** [comment]
@euclidianAce you contributed the neovim definitions... any tips on how to use them?

**Comment by euclidianAce** [comment]
I didn't really intend for the types to be generated out of the teal-types tree, what are the contents of your `tlconfig.lua`? This may be an unrelated issue since the autogen script doesn't try to preload any modules.

**Comment by B4mbus** [comment]
Yeah it was actually my fault, I had error in my tlconfig, sorry for that.
