### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by pdesaulniers** [teal-language/teal-types#7]
Considering that some changes such as https://github.com/teal-language/tl/pull/159 may break a few things in the declaration files, it would be a good idea to setup CI for this repo.

**Comment by hishamhm** [comment]
agreed! making it run `tl check` on all files would be a great start

**Comment by pdesaulniers** [comment]
This script could be useful to trigger a Travis job in `teal-types` when there is a new commit on `tl`'s master branch: https://github.com/plume-lib/trigger-travis/

**Comment by pdesaulniers** [comment]
Hmm, how do we handle includes? Right now, `luasec` depends on `luasocket`.

**Comment by hishamhm** [comment]
I would "install" them all into a single folder and then loop over them.

**Comment by pdesaulniers** [comment]
If we did this, then maybe there would be some naming conflicts? (say, two declaration files with the same name)

As mentioned in my edit above, maybe we could use `tlconfig.lua` for the purpose of including modules? (sorry, I tend to edit my comments a lot!)
